wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.32
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.6
    t:
      1:
      - 3
      2:
      - 3
      3:
      - 2
      4: 3.8.6
      5: 0.10.32
      8:
      - 4
      - 5
batch_size:
  desc: null
  value: 64
dataset:
  desc: null
  value: cifar10
decay:
  desc: null
  value: 0.96
dropout:
  desc: null
  value: 0.4
epochs:
  desc: null
  value: 10
image_channels:
  desc: null
  value: 3
image_size:
  desc: null
  value: 128
init_lr:
  desc: null
  value: 0.0005
model:
  desc: null
  value: MobileNetV2
n_classes:
  desc: null
  value: 10
test_size:
  desc: null
  value: 10000
train_size:
  desc: null
  value: 50000
trainable:
  desc: null
  value: false
